# Generated by Django 4.1.6 on 2023-02-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tc_compra',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tc_venta',
            field=models.FloatField(null=True),
        ),
    ]
